# Henrique Gomes Zanin NUSP: 10441321
# Gabriel Guimaraes Vilas Boas Marin NUSP: 11218521
all: compile

marin: compile-macos

compile-macos:
	@gcc-9 -o main *.c -I. -Wall -ansi

compile:
	@gcc -o main *.c -I. -Wall -ansi

run:
	@./main
